[package]
name = "abc180"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc180-a = { alias = "a", problem = "https://atcoder.jp/contests/abc180/tasks/abc180_a" }
abc180-b = { alias = "b", problem = "https://atcoder.jp/contests/abc180/tasks/abc180_b" }
abc180-c = { alias = "c", problem = "https://atcoder.jp/contests/abc180/tasks/abc180_c" }
abc180-d = { alias = "d", problem = "https://atcoder.jp/contests/abc180/tasks/abc180_d" }
abc180-e = { alias = "e", problem = "https://atcoder.jp/contests/abc180/tasks/abc180_e" }
abc180-f = { alias = "f", problem = "https://atcoder.jp/contests/abc180/tasks/abc180_f" }

[[bin]]
name = "abc180-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc180-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc180-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc180-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc180-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc180-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
