[package]
name = "abc161"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc161-a = { alias = "a", problem = "https://atcoder.jp/contests/abc161/tasks/abc161_a" }
abc161-b = { alias = "b", problem = "https://atcoder.jp/contests/abc161/tasks/abc161_b" }
abc161-c = { alias = "c", problem = "https://atcoder.jp/contests/abc161/tasks/abc161_c" }
abc161-d = { alias = "d", problem = "https://atcoder.jp/contests/abc161/tasks/abc161_d" }
abc161-e = { alias = "e", problem = "https://atcoder.jp/contests/abc161/tasks/abc161_e" }
abc161-f = { alias = "f", problem = "https://atcoder.jp/contests/abc161/tasks/abc161_f" }

[[bin]]
name = "abc161-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc161-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc161-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc161-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc161-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc161-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
