[package]
name = "abc192"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc192-a = { alias = "a", problem = "https://atcoder.jp/contests/abc192/tasks/abc192_a" }
abc192-b = { alias = "b", problem = "https://atcoder.jp/contests/abc192/tasks/abc192_b" }
abc192-c = { alias = "c", problem = "https://atcoder.jp/contests/abc192/tasks/abc192_c" }
abc192-d = { alias = "d", problem = "https://atcoder.jp/contests/abc192/tasks/abc192_d" }
abc192-e = { alias = "e", problem = "https://atcoder.jp/contests/abc192/tasks/abc192_e" }
abc192-f = { alias = "f", problem = "https://atcoder.jp/contests/abc192/tasks/abc192_f" }

[[bin]]
name = "abc192-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc192-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc192-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc192-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc192-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc192-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
