[package]
name = "abc171"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc171-a = { alias = "a", problem = "https://atcoder.jp/contests/abc171/tasks/abc171_a" }
abc171-b = { alias = "b", problem = "https://atcoder.jp/contests/abc171/tasks/abc171_b" }
abc171-c = { alias = "c", problem = "https://atcoder.jp/contests/abc171/tasks/abc171_c" }
abc171-d = { alias = "d", problem = "https://atcoder.jp/contests/abc171/tasks/abc171_d" }
abc171-e = { alias = "e", problem = "https://atcoder.jp/contests/abc171/tasks/abc171_e" }
abc171-f = { alias = "f", problem = "https://atcoder.jp/contests/abc171/tasks/abc171_f" }

[[bin]]
name = "abc171-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc171-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc171-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc171-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc171-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc171-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
