[package]
name = "abc181"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc181-a = { alias = "a", problem = "https://atcoder.jp/contests/abc181/tasks/abc181_a" }
abc181-b = { alias = "b", problem = "https://atcoder.jp/contests/abc181/tasks/abc181_b" }
abc181-c = { alias = "c", problem = "https://atcoder.jp/contests/abc181/tasks/abc181_c" }
abc181-d = { alias = "d", problem = "https://atcoder.jp/contests/abc181/tasks/abc181_d" }
abc181-e = { alias = "e", problem = "https://atcoder.jp/contests/abc181/tasks/abc181_e" }
abc181-f = { alias = "f", problem = "https://atcoder.jp/contests/abc181/tasks/abc181_f" }

[[bin]]
name = "abc181-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc181-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc181-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc181-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc181-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc181-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
