[package]
name = "abc183"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc183-a = { alias = "a", problem = "https://atcoder.jp/contests/abc183/tasks/abc183_a" }
abc183-b = { alias = "b", problem = "https://atcoder.jp/contests/abc183/tasks/abc183_b" }
abc183-c = { alias = "c", problem = "https://atcoder.jp/contests/abc183/tasks/abc183_c" }
abc183-d = { alias = "d", problem = "https://atcoder.jp/contests/abc183/tasks/abc183_d" }
abc183-e = { alias = "e", problem = "https://atcoder.jp/contests/abc183/tasks/abc183_e" }
abc183-f = { alias = "f", problem = "https://atcoder.jp/contests/abc183/tasks/abc183_f" }

[[bin]]
name = "abc183-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc183-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc183-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc183-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc183-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc183-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
