[package]
name = "abc168"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc168-a = { alias = "a", problem = "https://atcoder.jp/contests/abc168/tasks/abc168_a" }
abc168-b = { alias = "b", problem = "https://atcoder.jp/contests/abc168/tasks/abc168_b" }
abc168-c = { alias = "c", problem = "https://atcoder.jp/contests/abc168/tasks/abc168_c" }
abc168-d = { alias = "d", problem = "https://atcoder.jp/contests/abc168/tasks/abc168_d" }
abc168-e = { alias = "e", problem = "https://atcoder.jp/contests/abc168/tasks/abc168_e" }
abc168-f = { alias = "f", problem = "https://atcoder.jp/contests/abc168/tasks/abc168_f" }

[[bin]]
name = "abc168-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc168-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc168-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc168-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc168-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc168-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
