[package]
name = "abc185"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc185-a = { alias = "a", problem = "https://atcoder.jp/contests/abc185/tasks/abc185_a" }
abc185-b = { alias = "b", problem = "https://atcoder.jp/contests/abc185/tasks/abc185_b" }
abc185-c = { alias = "c", problem = "https://atcoder.jp/contests/abc185/tasks/abc185_c" }
abc185-d = { alias = "d", problem = "https://atcoder.jp/contests/abc185/tasks/abc185_d" }
abc185-e = { alias = "e", problem = "https://atcoder.jp/contests/abc185/tasks/abc185_e" }
abc185-f = { alias = "f", problem = "https://atcoder.jp/contests/abc185/tasks/abc185_f" }

[[bin]]
name = "abc185-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc185-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc185-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc185-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc185-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc185-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
