[package]
name = "abc170"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc170-a = { alias = "a", problem = "https://atcoder.jp/contests/abc170/tasks/abc170_a" }
abc170-b = { alias = "b", problem = "https://atcoder.jp/contests/abc170/tasks/abc170_b" }
abc170-c = { alias = "c", problem = "https://atcoder.jp/contests/abc170/tasks/abc170_c" }
abc170-d = { alias = "d", problem = "https://atcoder.jp/contests/abc170/tasks/abc170_d" }
abc170-e = { alias = "e", problem = "https://atcoder.jp/contests/abc170/tasks/abc170_e" }
abc170-f = { alias = "f", problem = "https://atcoder.jp/contests/abc170/tasks/abc170_f" }

[[bin]]
name = "abc170-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc170-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc170-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc170-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc170-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc170-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
