[package]
name = "abc163"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc163-a = { alias = "a", problem = "https://atcoder.jp/contests/abc163/tasks/abc163_a" }
abc163-b = { alias = "b", problem = "https://atcoder.jp/contests/abc163/tasks/abc163_b" }
abc163-c = { alias = "c", problem = "https://atcoder.jp/contests/abc163/tasks/abc163_c" }
abc163-d = { alias = "d", problem = "https://atcoder.jp/contests/abc163/tasks/abc163_d" }
abc163-e = { alias = "e", problem = "https://atcoder.jp/contests/abc163/tasks/abc163_e" }
abc163-f = { alias = "f", problem = "https://atcoder.jp/contests/abc163/tasks/abc163_f" }

[[bin]]
name = "abc163-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc163-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc163-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc163-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc163-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc163-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
