[package]
name = "abc174"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc174-a = { alias = "a", problem = "https://atcoder.jp/contests/abc174/tasks/abc174_a" }
abc174-b = { alias = "b", problem = "https://atcoder.jp/contests/abc174/tasks/abc174_b" }
abc174-c = { alias = "c", problem = "https://atcoder.jp/contests/abc174/tasks/abc174_c" }
abc174-d = { alias = "d", problem = "https://atcoder.jp/contests/abc174/tasks/abc174_d" }
abc174-e = { alias = "e", problem = "https://atcoder.jp/contests/abc174/tasks/abc174_e" }
abc174-f = { alias = "f", problem = "https://atcoder.jp/contests/abc174/tasks/abc174_f" }

[[bin]]
name = "abc174-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc174-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc174-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc174-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc174-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc174-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
