[package]
name = "abc178"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc178-a = { alias = "a", problem = "https://atcoder.jp/contests/abc178/tasks/abc178_a" }
abc178-b = { alias = "b", problem = "https://atcoder.jp/contests/abc178/tasks/abc178_b" }
abc178-c = { alias = "c", problem = "https://atcoder.jp/contests/abc178/tasks/abc178_c" }
abc178-d = { alias = "d", problem = "https://atcoder.jp/contests/abc178/tasks/abc178_d" }
abc178-e = { alias = "e", problem = "https://atcoder.jp/contests/abc178/tasks/abc178_e" }
abc178-f = { alias = "f", problem = "https://atcoder.jp/contests/abc178/tasks/abc178_f" }

[[bin]]
name = "abc178-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc178-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc178-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc178-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc178-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc178-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
