[package]
name = "abc164"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc164-a = { alias = "a", problem = "https://atcoder.jp/contests/abc164/tasks/abc164_a" }
abc164-b = { alias = "b", problem = "https://atcoder.jp/contests/abc164/tasks/abc164_b" }
abc164-c = { alias = "c", problem = "https://atcoder.jp/contests/abc164/tasks/abc164_c" }
abc164-d = { alias = "d", problem = "https://atcoder.jp/contests/abc164/tasks/abc164_d" }
abc164-e = { alias = "e", problem = "https://atcoder.jp/contests/abc164/tasks/abc164_e" }
abc164-f = { alias = "f", problem = "https://atcoder.jp/contests/abc164/tasks/abc164_f" }

[[bin]]
name = "abc164-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc164-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc164-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc164-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc164-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc164-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
